name: LSDA_A2
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.10.9
  - scikit-learn
  - scikit-learn-intelex
  - mlflow
  - azure-identity
  - influxdb
  - pip:
    - ewtpy
    - azureml-mlflow
    - azure-ai-ml

